# SPDX-License-Identifier: Apache-2.0
# Automated dependency-update PRs (Phase 4.2 / Phase 8.1). Every dependency is
# attack surface; keep the surface small and current.
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      python-deps:
        patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
