# SPDX-License-Identifier: Apache-2.0
# Sponsorship links surfaced on the repo (Phase 8.3). Placeholders for the
# example — replace or remove before going public.
# github: [your-org]
# open_collective: addlib
# custom: ["https://rosualinpetru.github.io/addlib/sponsor"]
